import type { ITrendingConfig, ITrendingRun, TrendingGenerationPreview } from "./trending.types"

export const MOCK_CONFIG: ITrendingConfig = {
  workspaceId: "mock-workspace-1",
  enabled: true,
  platforms: ["hackernews", "devto", "github", "reddit"],
  topics: ["react", "typescript", "devops", "AI"],
  industry: ["software development"],
  targetAudience: ["developers", "tech leads"],
  language: ["english"],
  postsPerPlatform: 5,
  topPostsForAI: 5,
  postsToGenerate: 3,
  scheduleType: "daily",
  scheduledTime: "09:00",
  scheduledDay: null,
  lastRunAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  nextRunAt: new Date(Date.now() + 22 * 60 * 60 * 1000),
  createdAt: new Date(),
  updatedAt: new Date(),
}

export const MOCK_RUNS: ITrendingRun[] = [
  {
    _id: "run-001",
    workspaceId: "mock-workspace-1",
    configSnapshot: MOCK_CONFIG,
    status: "completed",
    ranAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    sourceItems: [
      { source: "hackernews", title: "React 19 Compiler: What actually changed", url: "https://news.ycombinator.com", score: 847, rank: 1 },
      { source: "devto", title: "TypeScript 5.5 features you should know", url: "https://dev.to", score: 712, rank: 2 },
      { source: "github", title: "shadcn/ui — 80k stars and growing", url: "https://github.com", score: 634, rank: 3 },
      { source: "reddit", title: "Hot take: ORMs are slowing your team down", url: "https://reddit.com", score: 589, rank: 4 },
      { source: "hackernews", title: "We moved from k8s to plain Docker. Here's why", url: "https://news.ycombinator.com", score: 501, rank: 5 },
    ],
    generationIds: ["gen-001", "gen-002", "gen-003"],
    dismissed: false,
    error: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    _id: "run-002",
    workspaceId: "mock-workspace-1",
    configSnapshot: MOCK_CONFIG,
    status: "completed",
    ranAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
    sourceItems: [
      { source: "devto", title: "Building a design system in 2025", url: "https://dev.to", score: 920, rank: 1 },
      { source: "hackernews", title: "AI coding assistants: one year in", url: "https://news.ycombinator.com", score: 810, rank: 2 },
      { source: "reddit", title: "Stop using useEffect for data fetching", url: "https://reddit.com", score: 755, rank: 3 },
    ],
    generationIds: ["gen-004", "gen-005", "gen-006"],
    dismissed: false,
    error: null,
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
  },
  {
    _id: "run-003",
    workspaceId: "mock-workspace-1",
    configSnapshot: { ...MOCK_CONFIG, platforms: ["hackernews", "github"] },
    status: "failed",
    ranAt: new Date(Date.now() - 50 * 60 * 60 * 1000),
    sourceItems: [],
    generationIds: [],
    dismissed: false,
    error: "GitHub API rate limit exceeded",
    createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 50 * 60 * 60 * 1000),
  },
]

export const MOCK_GENERATIONS: TrendingGenerationPreview[] = [
  {
    generationId: "gen-001",
    runId: "run-001",
    sourceItem: { source: "hackernews", title: "React 19 Compiler: What actually changed", url: "https://news.ycombinator.com", score: 847, rank: 1 },
    topic: "React 19 Compiler: What actually changed\n\nSource: https://news.ycombinator.com",
    status: "completed",
    topVariant: {
      _id: "var-001",
      styleType: "thought-leadership",
      language: "English",
      hook: "The React 19 Compiler isn't just an optimization — it's a paradigm shift.",
      body: "For three years, we've been manually memoizing React components with useMemo and useCallback. React 19 makes most of that obsolete.\n\nHere's what actually changed:\n\n→ The compiler now analyzes your code statically\n→ It automatically inserts memoization where it matters\n→ You write normal code, it ships optimized code\n\nI tested this on a dashboard with 200+ components. Re-renders dropped by 60% without changing a single line of my code.\n\nThe era of manual optimization is ending.",
      cta: "What's your biggest React performance bottleneck right now?",
      hashtags: ["#React", "#WebDev", "#JavaScript", "#Frontend"],
      score: 92,
      engagement: 88,
      clarity: 94,
      formatting: 90,
      overallScore: 91,
      overallRank: 1,
      judgeReasoning: "Strong hook with a clear paradigm shift statement. Concrete data point (60% reduction) adds credibility. CTA invites discussion.",
    },
  },
  {
    generationId: "gen-002",
    runId: "run-001",
    sourceItem: { source: "devto", title: "TypeScript 5.5 features you should know", url: "https://dev.to", score: 712, rank: 2 },
    topic: "TypeScript 5.5 features you should know",
    status: "completed",
    topVariant: {
      _id: "var-002",
      styleType: "educational",
      language: "English",
      hook: "TypeScript 5.5 shipped quietly. The features it added will change how you write code daily.",
      body: "Most developers I know haven't upgraded yet. Here's why they should:\n\n1. Inferred type predicates — TS now narrows types through filter() automatically\n2. Regular expression syntax checking — invalid regex now caught at compile time\n3. Isolated declarations — faster parallel type-checking for large codebases\n\nThe inferred type predicates alone saved me ~40 type assertions in one refactor.\n\nTypeScript keeps getting better at getting out of your way.",
      cta: "Which of these features will you use first?",
      hashtags: ["#TypeScript", "#WebDev", "#JavaScript", "#Programming"],
      score: 85,
      engagement: 90,
      clarity: 86,
      formatting: 88,
      overallScore: 87,
      overallRank: 1,
      judgeReasoning: "Clear structure, numbered list aids readability. Personal anecdote with specific data strengthens credibility.",
    },
  },
  {
    generationId: "gen-003",
    runId: "run-001",
    sourceItem: { source: "github", title: "shadcn/ui — 80k stars and growing", url: "https://github.com", score: 634, rank: 3 },
    topic: "shadcn/ui — 80k stars and growing",
    status: "completed",
    topVariant: {
      _id: "var-003",
      styleType: "controversial",
      language: "English",
      hook: "shadcn/ui hit 80k GitHub stars. I think most teams are using it wrong.",
      body: "Everyone's copying the components into their repo. Almost nobody is reading why.\n\nShadcn's real value isn't the components — it's the philosophy:\n→ You own the code\n→ No version lock-in\n→ Accessibility built in by default\n\nI've seen teams install shadcn and immediately start overriding everything, defeating the purpose entirely.\n\nThe best UI library is the one your team actually understands.",
      cta: "Are you using shadcn/ui in production? What's your honest take?",
      hashtags: ["#WebDev", "#React", "#UIDesign", "#OpenSource"],
      score: 84,
      engagement: 82,
      clarity: 80,
      formatting: 85,
      overallScore: 83,
      overallRank: 1,
      judgeReasoning: "Contrarian hook drives curiosity. Clear perspective with actionable insight. Strong CTA for engagement.",
    },
  },
  {
    generationId: "gen-004",
    runId: "run-002",
    sourceItem: { source: "devto", title: "Building a design system in 2025", url: "https://dev.to", score: 920, rank: 1 },
    topic: "Building a design system in 2025",
    status: "completed",
    topVariant: {
      _id: "var-004",
      styleType: "educational",
      language: "English",
      hook: "We built a design system for 12 teams. Here's what we'd do differently.",
      body: "Lessons from 18 months of design system work:\n\n→ Start with tokens, not components\n→ Documentation is the product, not an afterthought\n→ Version your system like an API\n→ Measure adoption, not just delivery\n\nThe biggest mistake? We built what designers wanted instead of what engineers would actually use.",
      cta: "What's the hardest part of maintaining a design system at your company?",
      hashtags: ["#DesignSystem", "#WebDev", "#UIDesign", "#Engineering"],
      score: 90,
      engagement: 87,
      clarity: 91,
      formatting: 88,
      overallScore: 89,
      overallRank: 1,
      judgeReasoning: "Experience-based hook. Arrow-list format is highly scannable on LinkedIn. Strong closing insight.",
    },
  },
  {
    generationId: "gen-005",
    runId: "run-002",
    sourceItem: { source: "hackernews", title: "AI coding assistants: one year in", url: "https://news.ycombinator.com", score: 810, rank: 2 },
    topic: "AI coding assistants: one year in",
    status: "completed",
    topVariant: {
      _id: "var-005",
      styleType: "thought-leadership",
      language: "English",
      hook: "One year of daily AI coding tools. My honest verdict.",
      body: "I've used Cursor, Copilot, and Claude Code extensively. Here's the truth:\n\n✓ Boilerplate: AI wins every time\n✓ Debugging: AI helps, but you still need to understand the code\n✗ Architecture: AI suggestions are often confidently wrong\n✗ Security: Never trust AI-generated auth code without review\n\nThe developers getting the most value treat AI as a junior dev, not a senior one.\n\nExpectations calibration is the actual skill.",
      cta: "What's one thing AI tools do well — and one thing they get wrong — in your experience?",
      hashtags: ["#AI", "#Developer", "#CodingTools", "#Productivity"],
      score: 93,
      engagement: 91,
      clarity: 90,
      formatting: 92,
      overallScore: 92,
      overallRank: 1,
      judgeReasoning: "Balanced, honest framing builds trust. Checkmark format is highly scannable. Closing insight is quotable.",
    },
  },
  {
    generationId: "gen-006",
    runId: "run-002",
    sourceItem: { source: "reddit", title: "Stop using useEffect for data fetching", url: "https://reddit.com", score: 755, rank: 3 },
    topic: "Stop using useEffect for data fetching",
    status: "completed",
    topVariant: {
      _id: "var-006",
      styleType: "controversial",
      language: "English",
      hook: "useEffect for data fetching is a red flag in a React codebase. Here's why.",
      body: "I still see this pattern daily:\n\n```\nuseEffect(() => {\n  fetchData().then(setData)\n}, [])\n```\n\nIt causes: race conditions, missing loading states, no caching, no deduplication.\n\nThe React docs themselves say not to do this. Yet it's in every tutorial.\n\nUse React Query, SWR, or React 19 use(). They solve all four problems out of the box.\n\nWe owe it to junior devs to stop teaching the wrong pattern.",
      cta: "Which data fetching library do you use in production?",
      hashtags: ["#React", "#JavaScript", "#WebDev", "#Frontend"],
      score: 86,
      engagement: 92,
      clarity: 85,
      formatting: 89,
      overallScore: 88,
      overallRank: 1,
      judgeReasoning: "Code snippet grabs attention. Clear problem/solution structure. Final sentence creates moral urgency.",
    },
  },
]

export const MOCK_UNREAD_COUNT = 3
